spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_database
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080